security:
    # Configure password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # Configure user providers
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[mail]
                password_parameter: login[password]
                enable_csrf: true
                default_target_path: home
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /
            logout:
                path: logout
                # Uncomment if you want to redirect users to a specific page on logout
                # target: home

    access_control:
        # # autorise seulement les utilisateur connecté
        - { path: ^/addPost, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
